### ISSUE TITLE
Exception: Failed to authenticate with new TapoP100 script -> P110

### ISSUE THREAD

**Issue by Reiju** [almottier/TapoP100#16]
Hello
I have updated tapo python module to this one, unfortunately I am still getting odd error.

I am using correct parameters: 
device = PyP110.P110(device_ip, tapo_username, tapo_password,preferred_protocol="new")
TAPO P110 FW: 1.3.0

* not using .handshake() and .login()

Error:
```
Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/home/**/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "/home/**/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
```
ERROR:
Failed to initialize protocol

pip list:
pkcs7              0.1.2
pycryptodome       3.19.0
PyP100             0.1.4
requests           2.31.0

**Comment by Reiju** [comment]
Turns out that my creds were passed incorrectly. Works perfectly now.
