### ISSUE TITLE
Tapo P100 connection issue

### ISSUE THREAD

**Issue by sachinpatil280** [almottier/TapoP100#18]
Hi, I tried running the your code with my username, password and IP. 
Device Type: Tapo P100
Hardware version: 2.0
Firmware Version: 1.2.1

I am getting below response:

Traceback (most recent call last):
  File "C:\Users\xviewla\OneDrive - Konecranes Plc\Desktop\CodeBase\TapoP100-main\power_control.py", line 7, in <module>
    p100.handshake()  # Creates the cookies required for further methods
    ^^^^^^^^^^^^^^^^
  File "C:\Users\xviewla\OneDrive - Konecranes Plc\Desktop\CodeBase\TapoP100-main\PyP100\PyP100.py", line 136, in handshake
    encryptedKey = r.json()["result"]["key"]
                   ~~~~~~~~^^^^^^^^^^
KeyError: 'result'
Session:  <bound method Response.json of <Response [200]>>
Session:  {'error_code': 1003}
 
Process finished with exit code 1

**Comment by almottier** [comment]
Hello,
Could you make sure your credentials are correct using the official website:
https://tapo.tplinkcloud.com/tapo_web/#/login/signIn
