### ISSUE TITLE
Tap0 p100 failed to authentification 1003

### ISSUE THREAD

**Issue by MM-old** [almottier/TapoP100#30]
With this code I tried to use the Tapo P100  / P100
from PyP100 import PyP100
p100 = PyP100.P100("192.168.178.xx", "xxx@gmail.com", "password") # creates a P100 plug object
p100.getDeviceInfo()  # Returns dict with all the device info of the connected plug

I got this error message:
Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 35,                                                                                                                                                              in _initialize
    protocol.Initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", li                                                                                                                                                             ne 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
Error: {'error_code': 1003}
Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 35,                                                                                                                                                              in _initialize
    protocol.Initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", li                                                                                                                                                             ne 244, in Initialize
    result = self._request_raw("handshake", {"key": public_key})
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", li                                                                                                                                                             ne 173, in _request_raw
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: 1003
Traceback (most recent call last):
  File "/home/pi/solar/p100.py", line 10, in <module>
    p100.getDeviceInfo()  # Returns dict with all the device info of the connect                                                                                                                                                             ed plug
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 58,                                                                                                                                                              in getDeviceInfo
    return self.request("get_device_info")
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 46,                                                                                                                                                              in request
    self._initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 42,                                                                                                                                                              in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol
I use raspian os, python 3.9 and the actual firmware from Tapo. 
I have no ideas what I have to change.
Thanks for your help.

**Comment by marosg42** [comment]
What firmware is in your device? I updated fw in all my devices(6) yesterday and switched to this fork and all problems went away.

**Comment by MM-old** [comment]
Hi Marian,
thank you for your response.
I Have two devices.
No 1:
P100, Hardware Version EU/2.0
Firmware 1.2.5 Build 240411, Rel 143808
No 2:
P110, Hardware Version EU/1.20
Firmware 1.3.0 Build 230905 Rel 152200.
The app from tapo says,itis the aktual firmware.
Both devices do not work.
Now I have no ideas what I can do.
Best regards
Martin


Am Mo., 24. Juni 2024 um 09:20 Uhr schrieb Marian Gasparovic <
***@***.***>:

**Comment by almottier** [comment]
Hello,
try to log in using your credentials on https://tapo.tplinkcloud.com/tapo_web/#/login/signIn
you may need to create a new password, which should work with your script.

**Comment by MM-old** [comment]
Thank you very much. It works now perfect.
