### ISSUE TITLE
P100 - Failed to initialize protocol AuthProtocol

### ISSUE THREAD

**Issue by saepien** [almottier/TapoP100#34]
I have a P115 Smart Plug 
--

Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 35, in _initialize
    protocol.Initialize()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/auth_protocol.py", line 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
Error: {'error_code': 1003}
Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 35, in _initialize
    protocol.Initialize()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/auth_protocol.py", line 244, in Initialize
    result = self._request_raw("handshake", {"key": public_key})
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/auth_protocol.py", line 173, in _request_raw
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: 1003
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    p100.turnOn()
    ~~~~~~~~~~~^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 95, in turnOn
    return self.set_status(True)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 92, in set_status
    return self._set_device_info({"device_on": status})
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 64, in _set_device_info
    return self.request("set_device_info", params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 46, in request
    self._initialize()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 42, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol
>>>

**Comment by almottier** [comment]
Could you make sure your credentials are correct using the official website:
https://tapo.tplinkcloud.com/tapo_web/#/login/signIn

**Comment by danricho** [comment]
I have the same issue with one of my 4 P100s which was recently commissioned.
My login is working in the link above.

```
Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/share/tapo/venv/lib/python3.9/site-packages/PyP100/PyP100.py", line 35, in _initialize
    protocol.Initialize()
  File "/share/tapo/venv/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
Error: {'error_code': 1003}
Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "/share/tapo/venv/lib/python3.9/site-packages/PyP100/PyP100.py", line 35, in _initialize
    protocol.Initialize()
  File "/share/tapo/venv/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 244, in Initialize
    result = self._request_raw("handshake", {"key": public_key})
  File "/share/tapo/venv/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 173, in _request_raw
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: 1003
```

I am also having a "KLAP handshake failed" error using this [homebridge plugin](https://github.com/apatsufas/homebridge-tapo-p100). All other P100s are working with this as well.

**Comment by JanusHL** [comment]
Umm, I have check the new protocol and I receive the same error...

It seems the error is caused by "requests" module...

`  raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://192.168.20.103/app/handshake1`

**Comment by almottier** [comment]
Hello @Xylvier, I updated the project readme, thanks.

**Comment by Xylvier** [comment]
It's been a while...  and I found myself once again having the same problem with the authentication, I swear I tried all the same solutions again and it did not work. I have the app on my phone and could access it from there, 3rd party applications turned on as well. The code on the other hand, no changes (it worked back then, now, not so much).

I recently changed phones and while the application got transferred and works, there was something off, so I tried to change my password in the app, using the password I used in the code to authenticate, BIG surprise I got told the password was invalid!

I went online and requested a new password, which gives you a link.... 
After the new password was in place, the code ran, first try, no error.
Application on my phone told me I had to log in again.

So what do we make of that, phone app can work, code does not, error does not say password is wrong, BUT it can be the reason!
For all those that tried everything and still struggle, maybe try resetting the password and updating it in the code.

That said, thanks for sharing the help so far, I just thought since this is the place where most helpful information was condensed I'd share the latest weird, but solved issue "related".

Best regards,
Patrick
