### ISSUE TITLE
Still getting a 1003 error

### ISSUE THREAD

**Issue by Lars-the-tinkerer** [almottier/TapoP100#7]
Firstly thanks for your fork! Looks like most people are able to use their updated devices. I'm however still getting a 1003 error.
This is my traceback:
`Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
Error: {'error_code': 1003}
Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 244, in Initialize
    result = self._request_raw("handshake", {"key": public_key})
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/auth_protocol.py", line 173, in _request_raw
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: 1003
Traceback (most recent call last):
  File "/home/pi/test.py", line 9, in <module>
    p100.turnOn() #Turns the connected plug on
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 89, in turnOn
    return self.set_status(True)
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 86, in set_status
    return self._set_device_info({"device_on": status})
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 61, in _set_device_info
    return self.request("set_device_info", params)
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 43, in request
    self._initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 39, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol
`

**Comment by pasquale-98** [comment]
> Lars

same error

**Comment by almottier** [comment]
Could you make sure your credentials are correct using the official website:
https://tapo.tplinkcloud.com/tapo_web/#/login/signIn

**Comment by Lars-the-tinkerer** [comment]
> Could you make sure your credentials are correct using the official website: https://tapo.tplinkcloud.com/tapo_web/#/login/signIn

This is it thanks! Logging in there prompted a password reset as I only had numbers and they require at least 2 types characters now. Maybe we should add this in readme?
